networks:
  greenlight-sso-network:
    external: true

volumes:
  sso_postgres_data:

services:
  sso:
    container_name: sso_app
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./:/app
    networks:
      - default
      - greenlight-sso-network

  db:
    container_name: sso_db
    image: postgres:15-alpine
    volumes:
      - sso_postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.postgres