mode: "local"
access_token_ttl: 30m
refresh_token_ttl: 24h
activation_token_ttl: 68h
token_signing_alg: HS256
db:
  user: sso_user
  password: 1234
  host: localhost
  port: 5432
  name: sso
  load_timeout: 5s
server:
  port: 8080
  host: localhost
  timeout: 5s
  